### ISSUE TITLE
Can those algotirhm necesserily deployed on Franka Panda? Can it be deployed to other robotic arms

### ISSUE THREAD

**Issue by WeisonWEileen** [droid-dataset/droid_policy_learning#12]

**Comment by kpertsch** [comment]
The data is all collected on Franka Panda robot arms, so most likely the policies will only work on those arms.
However, if you are interested in other robot arms, check out the Open X-Embodiment dataset that contains data from a variety of arms, including the DROID dataset: https://robotics-transformer-x.github.io/
