### ISSUE TITLE
Can the policy trained be evaluated on simulation environments?

### ISSUE THREAD

**Issue by YY-GX** [droid-dataset/droid_policy_learning#17]
Hey, I don't have a Franka Robot for now, so can the policy trained with DROID be applied to some simulation environments (e.g., robomimic)? Thank you a lot if you could help :)

**Comment by kpertsch** [comment]
Thanks for the interest in our work! We haven't tried using DROID data for sim evaluation -- one thing that could be reasonable to try is co-training between a small dataset from your simulator and DROID -- I think going 0-shot from DROID to eval in a non-visually-realistic simulator like robomimic has little hope of success.

**Comment by YY-GX** [comment]
Gotcha! Thank you!!
