### ISSUE TITLE
RLDS format

### ISSUE THREAD

**Issue by Lizhuoling** [droid-dataset/droid_policy_learning#18]
Can you provide a guideline about what is contained in an RLDS data file? I find it is very difficult to understand how to read the content in droid and how to convert my own data to the RLDS format of droid. The Internet information is very messy.

**Comment by kpertsch** [comment]
You can find a detailed description of what fields are included in the RLDS format on your documentation page: https://droid-dataset.github.io/droid/the-droid-dataset.html#-dataset-schema
