### ISSUE TITLE
Would you like to add a simulator for easier evaluation?

### ISSUE THREAD

**Issue by StarCycle** [droid-dataset/droid_policy_learning#2]
Hi @kpertsch @droid-dataset ,

To reproduce your work we need a panda arm and setup the hardware. Is it possible to use a simulator which contains a panda arm?

For example, the [ARNOLD benchmark](https://github.com/arnold-benchmark/arnold) is based on Issac sim (quick enough) and contains a panda arm. It provides a small dataset with 8 tasks. 

- Is it suitable to train on the droid dataset, and evaluate ARNOLD?
- If it's not suitable, what kind of simulator do you recommend?
- Would you like to integrate the simulator into your repo? So everyone can train on droid and evaluate with a simulator in very low cost.

Best,
StarCycle

**Comment by ashwin-balakrishna96** [comment]
You can certainly collect data in your simulator and co-train with that data + DROID. Then you should be able to test out your policy in any simulator of your chance -- if the simulator has a Panda arm I would expect co-training with DROID to still be reasonably helpful.

**Comment by kpertsch** [comment]
Ah sorry just saw this! Agreed with Ashwin -- co-training should work with sim data. Evaluating in a simulator "0-shot" without any simulation data would probably be very hard, so def collect some sim data.

**Comment by StarCycle** [comment]
It makes sense! Thank you @kpertsch @ashwin-balakrishna96
