### ISSUE TITLE
How to add new modesl based on droid_policy_learning 

### ISSUE THREAD

**Issue by junjie-meng** [droid-dataset/droid_policy_learning#20]
Hi, thank you for your great work on Droid!

I am trying to use droid dataset to train my own model. Could you please specify how to add new models based on this repo ?

**Comment by kpertsch** [comment]
Hi!
This repo is a fork of robomimic, so you can add models like in robomimic, eg by adding them into `robomimic/models` (for architectures) and `models/algo` (for objectives / algorithms).
If you already have your model of choice implemented somewhere else, it could also be easier to simply copy out the data loader from [here](https://github.com/droid-dataset/droid_policy_learning/blob/205ff6b7ce00db271a3f729d3261a828fdc47fd2/robomimic/scripts/train.py#L158), which is a standard PyTorch Dataset, and paste it into your existing training loop!
