### ISSUE TITLE
What's the difference between "droid" and "droid-rlds" methods?

### ISSUE THREAD

**Issue by rsathua** [droid-dataset/droid_policy_learning#21]
Hi,

I see that you have two config files `droid_runs_language_conditioned_rlds.py `and `droid_runs_language_conditioned.py` and was wondering: what is the difference between these two methodologies? `droid_runs_language_conditioned` seems to have language as one of its observation modalities whereas its rlds counterpart does not. Does this mean that the rlds methodology does not use language conditioning?

I have observed the same pattern in [file_utils.py](https://github.com/droid-dataset/droid_policy_learning/blob/205ff6b7ce00db271a3f729d3261a828fdc47fd2/robomimic/utils/file_utils.py).

**Comment by kpertsch** [comment]
Hi!
the `_rlds` pathway uses the pre-compiled RLDS dataset, and this is the recommended approach for using DROID. Note that the RLDS pathway does in fact use language (we specify the language key to load from the dataset [here](https://github.com/droid-dataset/droid_policy_learning/blob/205ff6b7ce00db271a3f729d3261a828fdc47fd2/robomimic/scripts/train.py#L102)).

The non-rlds pathway is from earlier experiments in which we were loading not from RLDS, but we don't support this pathway anymore.

**Comment by rsathua** [comment]
Hi there! Thank you for your response. I see that the language key is defined in the train.py file. What I was struggling to locate in the code is where it actually was fed into the model. From my understanding it seems the observation keys defined in [file_utils.py](https://github.com/droid-dataset/droid_policy_learning/blob/205ff6b7ce00db271a3f729d3261a828fdc47fd2/robomimic/utils/file_utils.py) (which does not seem to include language) are the only inputs to the observation encoders / feature concatenation in [obs_nets.py](https://github.com/droid-dataset/droid_policy_learning/blob/205ff6b7ce00db271a3f729d3261a828fdc47fd2/robomimic/models/obs_nets.py#L312). Thanks again!
