### ISSUE TITLE
Run policy example fails

### ISSUE THREAD

**Issue by rtkg** [droid-dataset/droid_policy_learning#9]
Hi,

When trying out the provided [run_policy.ipynb](https://github.com/droid-dataset/droid_policy_learning/blob/master/examples/notebooks/run_policy.ipynb) notebook, it fails in the BC factory function [here](https://github.com/droid-dataset/droid_policy_learning/blob/4737f7e573cdb0a3aceb6fd30bbdc747936629c9/robomimic/algo/bc.py#L43). I think this is because the config that is loaded from the checkpoint has no `transformer` member. 

Maybe the example could be fixed by using a valid checkpoint?

**Comment by kpertsch** [comment]
I believe this example is from the original robomimic codebase we forked, so if you have trouble running it pls raise an issue in robomimic.
For inferencing our policies, please check out this section: https://github.com/droid-dataset/droid_policy_learning?tab=readme-ov-file#evaluating-trained-policies
